create database Customer_behavior
use Customer_behavior
select * from customer_table;

-- What is Total revenue generated by male  vs  female customers?
select gender,sum(purchase_amt) as Revenue
from customer_table
group by gender;

-- Which customers used discount but still spent more than the average purchase amount?
select customer_id,purchase_amt
from customer_table
where purchase_amt>
(
select avg(purchase_amt)
from customer_table
) and discount_applied='Yes';

-- Which are the top 5 products with the highest average review rating?
select top 5
item_purchased,cast(round(avg(review_rating),2 ) as Decimal(10,2)) as "Average Rating"
from customer_table
group by item_purchased
order by avg(review_rating) desc;

-- Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amt) as "Average"
from customer_table
where shipping_type in('Express','Standard')
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id) as "Total customer",
avg(purchase_amt) as "Average spend",
sum(purchase_amt) as "Total Revenue"
from customer_table
group by subscription_status;

-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
item_purchased,
SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0/ COUNT(*) AS discount_rate
FROM customer_table
GROUP BY item_purchased
ORDER BY discount_rate DESC;

-- Segment customers into New,Returning and Loyal based on their total
-- number of previous purchases and show count of each segement.
select customer_segment,count(*) as "customer_count"
from 
(select customer_id,previous_purchases,
case 
   when previous_purchases =1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
   end as customer_segment
from customer_table)as t
group by customer_segment;

-- What are the top 3 most purchased products within each category?
with item_counts as (
select category,item_purchased,count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_table
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer_table
where previous_purchases>5
group by subscription_status

-- What is the revenue contibution of each age group?
select age_group,sum(purchase_amt) as revenue_contribution
from customer_table
group by age_group
order by revenue_contribution desc;

-- Which season generates the highest revenue?
select season,sum(purchase_amt) as highest_revenue
from customer_table
group by season
order by highest_revenue desc ;

-- Which categories have the highest percentage of purchases with a discount applied?
select category,discount_rate
from(
select category,
sum(case when discount_applied='Yes' then 1 else 0 end)*100/count(*) as discount_rate
from customer_table
group by category)as t
order by discount_rate desc;

-- Which age group has the highest proportion of loyal customers?
select age_group,
round(sum(case 
    when previous_purchases > 10 then 1 
    else 0 
    end) * 100.0 / COUNT(*),2
    )as loyal_customer_percentage
from customer_table
group by age_group
order by loyal_customer_percentage desc;



